export const APP_LOAD = 'APP_LOAD';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_REDIRECT_TO = 'UPDATE_REDIRECT_TO';

export const CATEGORY_PAGE_LOADED = 'CATEGORY_PAGE_LOADED';
export const CATEGORY_PAGE_UNLOADED = 'CATEGORY_PAGE_UNLOADED';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_UNLOADED = 'ADD_CATEGORY_UNLOADED';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_LOADED = 'EDIT_CATEGORY_LOADED';
export const EDIT_CATEGORY_UNLOADED = 'EDIT_CATEGORY_UNLOADED';

export const PRODUCT_PAGE_LOADED = 'PRODUCT_PAGE_LOADED';
export const PRODUCT_PAGE_UNLOADED = 'PRODUCT_PAGE_UNLOADED';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_UNLOADED = 'ADD_PRODUCT_UNLOADED';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_LOADED = 'EDIT_PRODUCT_LOADED';
export const EDIT_PRODUCT_UNLOADED = 'EDIT_PRODUCT_UNLOADED';
